# Generated by Django 3.1.7 on 2021-03-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='created_at',
            new_name='created',
        ),
    ]
