# Generated by Django 3.1.7 on 2021-03-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0003_auto_20210306_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='url',
            new_name='photo_url',
        ),
    ]
