# Generated by Django 3.1.7 on 2021-03-07 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0004_auto_20210307_0606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvest',
            old_name='dry_Weight',
            new_name='dry_weight',
        ),
        migrations.RenameField(
            model_name='harvest',
            old_name='wet_Weight',
            new_name='wet_weight',
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvests.farm'),
        ),
    ]
