# Generated by Django 3.1.7 on 2021-03-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0005_auto_20210307_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
