# Generated by Django 3.1.7 on 2021-03-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0007_auto_20210307_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
